/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanager;

import com.mysql.cj.jdbc.Blob;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shubh
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form category
     */
    public User() {
        initComponents();
        initCustomSetup();
    }
    
    JFileChooser chooser;
    BufferedImage img;
    File file ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        showProfile = new javax.swing.JLabel();
        showInventory = new javax.swing.JLabel();
        jSplitProfile = new javax.swing.JSplitPane();
        jPanelUpdatePass3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnUpdatePass3 = new javax.swing.JButton();
        tfCurrentPass3 = new javax.swing.JPasswordField();
        tfNewPass3 = new javax.swing.JPasswordField();
        tfConfirmNewPass3 = new javax.swing.JPasswordField();
        jPanelSignup = new javax.swing.JPanel();
        tfEmailR = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        dropdownSalutation = new javax.swing.JComboBox<>();
        tfFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfLastName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        tfAddressR = new javax.swing.JTextField();
        tfMobileR = new javax.swing.JTextField();
        inventoryPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aiName = new javax.swing.JTextField();
        aiImageUpload = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dropdownAICategory = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        aiquantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dropdownAIUnit = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        aiUnitPrice = new javax.swing.JTextField();
        dropdownAIStatus = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnUpdateItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setIcon(new javax.swing.ImageIcon("F:\\Mpirimpa\\Assets\\Sprites\\Menu\\Create Table\\Cross.png")); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setOpaque(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        showProfile.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        showProfile.setForeground(new java.awt.Color(255, 255, 255));
        showProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\shubh\\OneDrive\\Desktop\\listener.png")); // NOI18N
        showProfile.setText("Profile");
        showProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showProfileMouseClicked(evt);
            }
        });

        showInventory.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        showInventory.setForeground(new java.awt.Color(125, 125, 125));
        showInventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showInventory.setText("Inventory");
        showInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showInventoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );

        jSplitProfile.setDividerLocation(600);
        jSplitProfile.setMaximumSize(new java.awt.Dimension(1250, 500));
        jSplitProfile.setMinimumSize(new java.awt.Dimension(1250, 500));

        jPanelUpdatePass3.setPreferredSize(new java.awt.Dimension(500, 350));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("current password");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("new password");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("confirm password");

        btnUpdatePass3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdatePass3.setText("update");
        btnUpdatePass3.setPreferredSize(new java.awt.Dimension(100, 35));
        btnUpdatePass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassActionPerformed(evt);
            }
        });

        tfNewPass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNewPass3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUpdatePass3Layout = new javax.swing.GroupLayout(jPanelUpdatePass3);
        jPanelUpdatePass3.setLayout(jPanelUpdatePass3Layout);
        jPanelUpdatePass3Layout.setHorizontalGroup(
            jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdatePass3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelUpdatePass3Layout.createSequentialGroup()
                        .addGroup(jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdatePass3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNewPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfConfirmNewPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelUpdatePass3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCurrentPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUpdatePass3Layout.setVerticalGroup(
            jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUpdatePass3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCurrentPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNewPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelUpdatePass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfConfirmNewPass3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnUpdatePass3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(493, 493, 493))
        );

        jSplitProfile.setRightComponent(jPanelUpdatePass3);

        jPanelSignup.setOpaque(false);
        jPanelSignup.setPreferredSize(new java.awt.Dimension(500, 350));

        tfEmailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailRActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("email*");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdate.setText("update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 35));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        dropdownSalutation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dropdownSalutation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Ms.", "Mrs." }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("F. Name*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("L. Name*");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("address");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("mobile");

        rbMale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbMale.setSelected(true);
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        rbFemale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });

        tfAddressR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressRActionPerformed(evt);
            }
        });

        tfMobileR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMobileRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignupLayout = new javax.swing.GroupLayout(jPanelSignup);
        jPanelSignup.setLayout(jPanelSignupLayout);
        jPanelSignupLayout.setHorizontalGroup(
            jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignupLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSignupLayout.createSequentialGroup()
                        .addComponent(dropdownSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSignupLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSignupLayout.createSequentialGroup()
                                .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfMobileR, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelSignupLayout.createSequentialGroup()
                        .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAddressR)
                            .addComponent(tfEmailR)
                            .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelSignupLayout.setVerticalGroup(
            jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignupLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmailR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddressR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMobileR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addGap(35, 35, 35)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        jSplitProfile.setLeftComponent(jPanelSignup);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("name");

        aiName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        aiName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiNameActionPerformed(evt);
            }
        });

        aiImageUpload.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        aiImageUpload.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        aiImageUpload.setIcon(new javax.swing.ImageIcon("F:\\Mpirimpa\\Assets\\Sprites\\Menu\\Create Table\\Plus.png")); // NOI18N
        aiImageUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aiImageUploadMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("category");

        dropdownAICategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dropdownAICategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Category 1", "Category 2", "Category 3", "Category 4", "Category 5" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("quantity");

        aiquantity.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        aiquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiquantityActionPerformed(evt);
            }
        });
        aiquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aiquantityKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("unit");

        dropdownAIUnit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dropdownAIUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unit 1", "Unit 2", "Unit 3", "Unit 4", "Unit 5" }));

        jLabel23.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("unit price");

        aiUnitPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        aiUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiUnitPriceActionPerformed(evt);
            }
        });
        aiUnitPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aiUnitPriceKeyPressed(evt);
            }
        });

        dropdownAIStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dropdownAIStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel24.setText("image");

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel25.setText("status");

        btnAddItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddItem.setText("ADD");
        btnAddItem.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItembtnUpdatePassActionPerformed(evt);
            }
        });

        btnUpdateItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdateItem.setText("UPDATE");
        btnUpdateItem.setPreferredSize(new java.awt.Dimension(100, 35));
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItembtnUpdatePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aiImageUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(aiName)
                                .addComponent(dropdownAICategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(aiquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dropdownAIUnit, 0, 200, Short.MAX_VALUE)
                                .addComponent(aiUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dropdownAIStatus, 0, 200, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(btnUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aiName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdownAICategory, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aiquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdownAIUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aiUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdownAIStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(aiImageUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Quantity", "Unit", "Unit Price", "Status", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(inventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(inventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfEmailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailRActionPerformed

    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt){
        try {
            char[] currentPass = tfCurrentPass3.getPassword();
            char[] newPass = tfNewPass3.getPassword();
            char[] confirmNewPass = tfConfirmNewPass3.getPassword();
            
            if(currentPass==null || currentPass.length <= 0 || newPass==null || newPass.length <= 0 || confirmNewPass==null || confirmNewPass.length <= 0){
                JOptionPane.showMessageDialog(null, "some fields are empty", "Woops", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(!DatabaseManager.getInstance().CheckPass(String.valueOf(currentPass))){
                JOptionPane.showMessageDialog(null, "enter valid current password", "Woops", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(!Arrays.equals(newPass, confirmNewPass)){
                JOptionPane.showMessageDialog(null, "new passwords do not match.", "Woops", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(DatabaseManager.getInstance().UpdateUserPassword(String.valueOf(newPass))){
                JOptionPane.showMessageDialog(null, "updated successfully");
                refreshProfileData();
            }else{
                JOptionPane.showMessageDialog(null, "updation failed, try again.", "Woops", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "some error occured", "Woops", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String salutation = dropdownSalutation.getSelectedItem().toString();
        String fname = tfFirstName.getText().trim();
        String lname = tfLastName.getText().trim();
        String email = tfEmailR.getText().trim();
        String address = tfAddressR.getText();
        String mobile = tfMobileR.getText();
        String gender = getSelectedButtonText(btnGroupGender);
        if(gender == null || gender.isEmpty())
            gender = "Male";
        if(salutation == null || salutation.isEmpty())
            salutation = "Mr.";
        if(email.isEmpty() || fname.isEmpty() || lname.isEmpty() || salutation.isEmpty()){
            JOptionPane.showMessageDialog(null, "some fields are empty", "Woops", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!DataValidator.validateEmail(email)){
            JOptionPane.showMessageDialog(null, "invalid email format", "Woops", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(mobile == null || mobile.isEmpty())
            mobile = "";
        else{
            if(!DataValidator.validateMobile(mobile)){
                JOptionPane.showMessageDialog(null, "invalid mobile number format", "Woops", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        System.out.println("full name: "+salutation+" "+fname+" "+lname);
        try {
            if(!email.equals(Profile.getEmail())){
                if(emailExists(email)){
                    JOptionPane.showMessageDialog(null, "a user with entered email already exists.", "Woops", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if(DatabaseManager.getInstance().UpdateUserData(fname, lname, email, mobile, gender, address, salutation)){
                JOptionPane.showMessageDialog(null, "updated successfully");
                refreshProfileData();
            }else{
                JOptionPane.showMessageDialog(null, "updation failed, try again.", "Woops", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "some error occured", "Woops", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private boolean emailExists(String email) throws SQLException{
        return DatabaseManager.getInstance().emailExists(email);
    }
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    
    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void tfAddressRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressRActionPerformed

    private void tfMobileRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMobileRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMobileRActionPerformed

    private void tfNewPass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNewPass3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNewPass3ActionPerformed

    private void showInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showInventoryMouseClicked
        if(jSplitProfile.isVisible()){
            jSplitProfile.setVisible(false);
            showProfile.setForeground(new java.awt.Color(125, 125, 125));
            showInventory.setForeground(new java.awt.Color(255, 255, 255));
            inventoryPanel.setVisible(true);
        }
    }//GEN-LAST:event_showInventoryMouseClicked

    private void showProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showProfileMouseClicked
        if(!jSplitProfile.isVisible()){
            inventoryPanel.setVisible(false);
            showInventory.setForeground(new java.awt.Color(125, 125, 125));
            showProfile.setForeground(new java.awt.Color(255, 255, 255));
            jSplitProfile.setVisible(true);
        }
    }//GEN-LAST:event_showProfileMouseClicked

    private void aiNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aiNameActionPerformed

    String path = null;
    
    private void aiImageUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aiImageUploadMouseClicked
        chooser = new JFileChooser();
        int i=chooser.showOpenDialog(jPanel1);
        if(i!=JFileChooser.APPROVE_OPTION)
            return;
        file = chooser.getSelectedFile();
        path = file.getAbsolutePath();
        try {
            img=ImageIO.read(file);
            
            ImageIcon icon= resizeImage(img, aiImageUpload.getWidth(), aiImageUpload.getHeight());
            aiImageUpload.setIcon(icon); // ADDED
            //Dimension imageSize = new Dimension(icon.getIconWidth(),icon.getIconHeight()); // ADDED
            //imageUpload.setPreferredSize(imageSize); // ADDED

            aiImageUpload.revalidate(); // ADDED
            aiImageUpload.repaint(); // ADDED
        }
        catch(IOException e1) {}
    }//GEN-LAST:event_aiImageUploadMouseClicked

    private void aiquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aiquantityActionPerformed

    private void aiquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aiquantityKeyPressed
        String value = aiquantity.getText();
            int l = value.length();
            if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)
            {  
                if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
                aiquantity.setEditable(true);
                } else {
                   aiquantity.setEditable(false);
                }
            }else{
                aiquantity.setEditable(true);
            }
    }//GEN-LAST:event_aiquantityKeyPressed

    private void aiUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aiUnitPriceActionPerformed

    private void aiUnitPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aiUnitPriceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aiUnitPriceKeyPressed

    private void btnAddItembtnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItembtnUpdatePassActionPerformed
        try {
            if(aiName.getText().isEmpty() || aiquantity.getText().isEmpty() || aiUnitPrice.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "some fields are empty.", "Woops", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String name = aiName.getText();
            String category = dropdownAICategory.getSelectedItem().toString();
            String unit = dropdownAIUnit.getSelectedItem().toString();
            InputStream image = null;
            if(path != null && !path.isEmpty()){
                File f = new File(path);
                image = new FileInputStream(f);
            }
            int quantity = Integer.parseInt(aiquantity.getText().trim());
            int unitprice = Integer.parseInt(aiUnitPrice.getText().trim());
            String status = dropdownAIStatus.getSelectedItem().toString();
            if(DatabaseManager.getInstance().AddItem(name, category, unit, image, quantity, unitprice, status)){
                aiName.setText("");
                path = null;
                aiquantity.setText("");
                aiUnitPrice.setText("");
                //aiImageUpload.setIcon(new ImageIcon(getClass().getResource("/images/Plus.png")));
                updateItemList();
            }else{
                JOptionPane.showMessageDialog(null, "failed to add item, try again.", "Woops", JOptionPane.ERROR_MESSAGE);
            }
        } catch (FileNotFoundException | SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "some error occured", "Woops", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddItembtnUpdatePassActionPerformed

    int selectedItemId = -1;
    
    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        DefaultTableModel d = (DefaultTableModel)itemTable.getModel();
        int selected = itemTable.getSelectedRow();
        selectedItemId = Integer.parseInt(d.getValueAt(selected, 0).toString());
        aiName.setText(d.getValueAt(selected, 1).toString());
        dropdownAICategory.setSelectedItem(d.getValueAt(selected, 2).toString());
        aiquantity.setText(d.getValueAt(selected, 3).toString());
        dropdownAIUnit.setSelectedItem(d.getValueAt(selected, 4).toString());
        aiUnitPrice.setText(d.getValueAt(selected, 5).toString());
        dropdownAIStatus.setSelectedItem(d.getValueAt(selected, 6).toString());
        btnAddItem.setVisible(false);
        btnUpdateItem.setVisible(true);
    }//GEN-LAST:event_itemTableMouseClicked

    private void btnUpdateItembtnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItembtnUpdatePassActionPerformed
        try {
            if(aiName.getText().isEmpty() || aiquantity.getText().isEmpty() || aiUnitPrice.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "some fields are empty.", "Woops", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String name = aiName.getText();
            String category = dropdownAICategory.getSelectedItem().toString();
            String unit = dropdownAIUnit.getSelectedItem().toString();
            InputStream image = null;
            if(path != null && !path.isEmpty()){
                File f = new File(path);
                image = new FileInputStream(f);
            }
            int quantity = Integer.parseInt(aiquantity.getText().trim());
            int unitprice = Integer.parseInt(aiUnitPrice.getText().trim());
            String status = dropdownAIStatus.getSelectedItem().toString();
            if(DatabaseManager.getInstance().UpdateItem(selectedItemId, name, category, unit, image, quantity, unitprice, status)){
                aiName.setText("");
                path = null;
                aiquantity.setText("");
                aiUnitPrice.setText("");
                btnAddItem.setVisible(true);
                btnUpdateItem.setVisible(false);
                //aiImageUpload.setIcon(new ImageIcon(getClass().getResource("/images/Plus.png")));
                updateItemList();
            }else{
                JOptionPane.showMessageDialog(null, "failed to add item, try again.", "Woops", JOptionPane.ERROR_MESSAGE);
            }
        } catch (FileNotFoundException | SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "some error occured", "Woops", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateItembtnUpdatePassActionPerformed

    private void updateItemList(){
        try {
            Vector<Vector<String>> items = DatabaseManager.getInstance().GetMyItems();
            DefaultTableModel d = (DefaultTableModel)itemTable.getModel();
            d.getDataVector().removeAllElements();
            d.fireTableDataChanged();
            for(Vector<String> v : items)
                d.addRow(v);
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private ImageIcon resizeImage(BufferedImage image, int width, int height) {

    // image - BufferedImage object of your file selected
    // width - Width of your JLabel
    // height - Height of yout JLabel

    // Creating a temporary Image of your desired size.
    BufferedImage tempImg = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g = tempImg.createGraphics();

    g.drawImage(image, 0, 0, width, height, null); // Draw the selected image on the tempImage from co-ordinates (0, 0) to (width, height) of the tempImage.
    g.dispose();  // Clear resources.

    return new ImageIcon(tempImg);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aiImageUpload;
    private javax.swing.JTextField aiName;
    private javax.swing.JTextField aiUnitPrice;
    private javax.swing.JTextField aiquantity;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupGender;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JButton btnUpdatePass;
    private javax.swing.JButton btnUpdatePass1;
    private javax.swing.JButton btnUpdatePass2;
    private javax.swing.JButton btnUpdatePass3;
    private javax.swing.JComboBox<String> dropdownAICategory;
    private javax.swing.JComboBox<String> dropdownAIStatus;
    private javax.swing.JComboBox<String> dropdownAIUnit;
    private javax.swing.JComboBox<String> dropdownSalutation;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JTable itemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSignup;
    private javax.swing.JPanel jPanelUpdatePass;
    private javax.swing.JPanel jPanelUpdatePass1;
    private javax.swing.JPanel jPanelUpdatePass2;
    private javax.swing.JPanel jPanelUpdatePass3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitProfile;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JLabel showInventory;
    private javax.swing.JLabel showProfile;
    private javax.swing.JTextField tfAddressR;
    private javax.swing.JTextField tfConfirmNewPass;
    private javax.swing.JTextField tfConfirmNewPass1;
    private javax.swing.JTextField tfConfirmNewPass2;
    private javax.swing.JPasswordField tfConfirmNewPass3;
    private javax.swing.JTextField tfCurrentPass;
    private javax.swing.JTextField tfCurrentPass1;
    private javax.swing.JTextField tfCurrentPass2;
    private javax.swing.JPasswordField tfCurrentPass3;
    private javax.swing.JTextField tfEmailR;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfMobileR;
    private javax.swing.JTextField tfNewPass;
    private javax.swing.JTextField tfNewPass1;
    private javax.swing.JTextField tfNewPass2;
    private javax.swing.JPasswordField tfNewPass3;
    // End of variables declaration//GEN-END:variables

    private void initCustomSetup() {
        //this.setVisible(false);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        //this.setUndecorated(true);
        //this.setVisible(true);
        btnAddItem.setVisible(true);
                btnUpdateItem.setVisible(false);
        jSplitProfile.setVisible(false);
            showProfile.setForeground(new java.awt.Color(125, 125, 125));
            showInventory.setForeground(new java.awt.Color(255, 255, 255));
            inventoryPanel.setVisible(true);
        btnGroupGender.add(rbMale);
        btnGroupGender.add(rbFemale);
        refreshProfileData();
        updateItemList();
    }

    private void refreshProfileData() {
        try {
            tfCurrentPass3.setText("");
            tfNewPass3.setText("");
            tfConfirmNewPass3.setText("");
            DatabaseManager.getInstance().loadProfile();
            tfFirstName.setText(Profile.getFname());
            tfLastName.setText(Profile.getLname());
            String sal = Profile.getSalutation();
            dropdownSalutation.setSelectedIndex(sal.equalsIgnoreCase("mrs.") ? 2 : sal.equalsIgnoreCase("ms.") ? 1 : 0);
            tfEmailR.setText(Profile.getEmail());
            tfAddressR.setText(Profile.getAddress());
            tfMobileR.setText(Profile.getMobile());
            String g = Profile.getGender();
            rbFemale.setSelected(g.equalsIgnoreCase("female"));
            rbMale.setSelected(!g.equalsIgnoreCase("female"));
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}